import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import  imageUrlBuilder from '@sanity/image-url'

const inter = Inter({ subsets: ['vietnamese'] })
export default function Home({ posts }) {
  console.log(posts)
  const [mappedPosts, setMappedPosts] = useState([]);

  useEffect(() => {
    if (posts.length) {
      const imgBuilder = imageUrlBuilder({
        projectId: 'fcvw42nl',
        dataset: 'production',
      });

      setMappedPosts(
        posts.map(p => {
          return {
            ...p,
            mainImage: imgBuilder.image(p.mainImage),
          }
        })
      );
    }else {
      setMappedPosts([]);
    }
  }, [posts]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
                <p className={styles.logo}>
              DANIELLE DYER - Photographer</p>
            
          </div>
        </div>

        <div className={styles.center}>
          <h1 className={styles.h1}>dannii dyer</h1>
        </div>
          <div className={styles.center}>
          <h1 className={inter.className}>Recent Posts...</h1>
        </div>

          
        <div className={styles.container_all}>
          {mappedPosts.length ? mappedPosts.map((p, index) => (
            <div className={styles.container}>
              <div key={index} className={styles.p}>
                <img src={p.mainImage}
                  alt="13"
                  width={300}
                  height={231} />
                <span className={styles.title}>{p.title}</span>
                <span className={styles.text}>{p.body.text}</span>
                </div>
                </div>
                )) : <>No Posts Yet</>}
            </div>

            {/* <div className={styles.grid}>
                {mappedPosts.length ? mappedPosts.map((p, index) => (
                  <div className={styles.card}>
                    <div key={index} className={styles.p}>
                      <img
                        src={p.mainImage}
                        alt="13"
                        width={300}
                        height={231} />
                      <h2 className={inter.className}>{p.title}</h2>
                      <p className={inter.className}>{p.body.text}Click card for more details...</p>
                    </div>
                  </div>
                )) : <>No Posts Yet</>}
          </div> */}
      </main>
    </>
  )
}

export const getServerSideProps = async pageContext => {
  const query = encodeURIComponent(`*[ _type == "post"]`);
  const url = `https://fcvw42nl.api.sanity.io/v1/data/query/production?query=${query}`;
  
  const result = await fetch(url)
  .then(res => res.json());

  if (!result.result || !result.result.length) {
      return {
          props: {
            posts: [],
          }
      }
  }else {
      return {
          props: {
            posts: result.result,
          }
      }
  }
};
